### ISSUE TITLE
Add ssl configuration to s3 storage

### ISSUE THREAD

**Issue by AntonFriberg** [polyaxon/polystores#1]
Hi!

During testing with self hosted s3 alternatives it is of great importance to be able to configure the s3 client to not use ssl or not verify the ssl. `boto3.session.Session.client` can be given such configurations as is specified here:  https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client

What I would like to have is the ability to specify these options with the already available configurations. So for example in my cloud storage `key.json` I would specify

```diff
{
    "AWS_ENDPOINT_URL": "https://storage.example.com:8082",
    "AWS_ACCESS_KEY_ID": "<< access-key >>",
    "AWS_SECRET_ACCESS_KEY": "<< secret-access-key >>",
    "AWS_SECURITY_TOKEN": "<< security-token >>",
    "AWS_REGION": "us-east-1",
+   "AWS_USE_SSL": true,
+   "AWS_VERIFY_SSL": false
}
```

Those configurations would then be picked up in the client setup here https://github.com/polyaxon/polystores/blob/master/polystores/clients/aws_client.py#L60

So something like this:

```diff
    def get_aws_client(client_type,
                       endpoint_url=None,
                       aws_access_key_id=None,
                       aws_secret_access_key=None,
                       aws_session_token=None,
                       region_name=None,
+                      aws_use_ssl=True,
+                      aws_verify_ssl=None):
        
        session = get_aws_session(aws_access_key_id=aws_access_key_id,
                                  aws_secret_access_key=aws_secret_access_key,
                                  aws_session_token=aws_session_token,
                                  region_name=region_name)
        endpoint_url = endpoint_url or get_endpoint_url()
+       aws_use_ssl = aws_use_ssl or get_aws_use_ssl()
+       aws_verify_ssl = aws_verify_ssl or get_aws_verify_ssl()
        
        return session.client(client_type,
                              endpoint_url=endpoint_url,
+                             use_ssl=aws_use_ssl,
+                             verify=aws_verify_ssl)
```

I can try to provide a PR if you would like?

Finally I want you to know that I see great potential in polyaxon and appreciate all the work you have put in so far! Many thanks!

**Comment by mouradmourafiq** [comment]
@AntonFriberg the proposed config extension makes sense, a PR will be appreciated.
