### ISSUE TITLE
Bug: botocore.exceptions.ParamValidationError on s3 store ls command

### ISSUE THREAD

**Issue by afilippi** [polyaxon/polystores#12]
I was having an issue where my S3 outputs weren't showing up in the polyaxon UI despite being saved correctly to the S3 bucket. 

Tracked it down to this call https://github.com/polyaxon/polyaxon/blob/0.4.4/polyaxon/api/experiments/views.py#L430 which is calling the `ls` on our S3 Store. 

Tracked that down to https://github.com/polyaxon/polystores/blob/master/polystores/stores/s3_store.py#L207 which appears to be sending the full path as if it were a bucket name, which I believe to be the cause of this issue. 

I've got a test case and fix in another fork that's ready for a PR if you think I've diagnosed this correctly. https://github.com/polyaxon/polystores/compare/master...afilippi:FRST-263-S3Parse?expand=1

**Comment by mouradmourafiq** [comment]
it might be related to this issue #5?

**Comment by mouradmourafiq** [comment]
@afilippi a PR is appreciated 👍
