### ISSUE TITLE
Polystores: Empty file result in download_dir() causes IsADirectoryError 

### ISSUE THREAD

**Issue by adam-phillipps** [polyaxon/polystores#15]
I am hoping to either report a bug or get clarification on how I'm doing user error when trying to download a directory and its contents, including another subdirectory, using the `store.download_dir()` method.

My issue is that when I try, even after recreating a bucket and manually uploading test files, I get an `IsADirectoryError` during the download.

It seems to be happening because `results = self.list(...)` ( on `polystores/stores/gcs_store.py#307 download_dir()`) gets back one blob that has an empty name. That empty name is then used on line 324 as the file name in the `local_path` to `self.download_file`, the error happens because it's trying to download the blob to a directory name, locally. 

Here's the short version of the chain of events that seem to me to be causing my issue:
I believe it happens in part because of this line:
https://github.com/polyaxon/polystores/blob/master/polystores/stores/gcs_store.py#L323
```
# from my_script.py
store.download_dir('gs://my-bucket/testing/', '/data/proj/images', 'use_basename': False)

# which calls self.list() on line polystores/stores/gcs_store.py#307 like this
results = self.list(bucket_name='my-bucket', key='testing/', delimiter='/')

# which produces a result that looks like this
{ 'blobs': [
        ('', 11), # this is the empty file I mentioned
        ('some_file.jpg', 4303315),
        ('another_img.jpg', 4523409),
        ...,
        ('test_images.tar', 32729088)],
  'prefixes': [sub_dir_i_created_in_the_bucket_that_holds_other_files]}

# and later in the `download_dir()` method, it uses the result of self.list()
# to run self.download_file() on #324
self.download_file(blob='testing/',
                   local_path='/data/proj/images',
                   bucket_name='my-bucket',
                   use_basename=False)

IsADirectoryError: [Errno 21] Is a directory: '/data/proj/images'
```

**My environment looks like this:**
I'm using the `tensorflow:latest-py3` Docker image, which has
Ubuntu 18.04.2 LTS
Python:    3.6.8

and the project is using
polystores:    0.2.3
google-cloud-storage:    1.17.0

**Steps to reproduce** (this could all be user error so my steps might not work for you)
I'm able to reproduce this by attempting to run the `download_dir` method, using the google storage client on a bucket with a similar tree.  For this example bucket, I would be requesting to download the `parent_dir_2` namespace, including all files and "subdirectories" in the bucket.
```
.
├── parent_dir_1
├── parent_dir_2
│   ├── sub_dir_1
│   │   └── file_2
│   │   └── file_3
│   │   └── file_4
│   └── file_1
```
by invoking the method like this
```
store.download_dir('gs://my-bucket/parent_dir_2/', '/data/proj/images', 'use_basename': False)
```

**Notes and observations:**
If I step through the code in a debugger and `results['blobls'].pop(0)` off the troublesome blob before the download, in  `polystores/stores/gcs_store.py#324` during `self.download_file(...)`, the method finishes with no error and I get the files and subdirectories on my local disk, like I expect them.

**Comment by mouradmourafiq** [comment]
thanks for reporting this issue. I will also investigate on my end.

**Comment by adam-phillipps** [comment]
I've been trying to see if an idea I had would work.  It passes the specs in master but i'm not sure if I'm missing the point of that empty blob or if there's a better place to try to fix that, if it is a bug.
The change I've been looking at would be a simple filter on line 309.  Maybe something like...
```
# polystores/stores/gcs_store.py#L309
308:     results = self.list(bucket_name=bucket_name, key=blob, delimiter='/')
309:     results['blobs'] = list(filter(lambda b: b[0], results['blobs'])) # new line
```

**Comment by mouradmourafiq** [comment]
I could not reproduce even with the structure. If you can produce a minimal script that generate some dump files and upload them to a bucket, and then fails when downloading them, that would be great to further debug the issue.

**Comment by adam-phillipps** [comment]
OK, I believe I've got a script you can run that should reproduce it.
I tried to upload the files but it doesn't like my extensions so here's a gist.
https://gist.github.com/adam-phillipps/8ddbef195044d32fe06ca6743a3360b8

**Comment by mouradmourafiq** [comment]
Thanks for putting this together, I will try it out tomorrow and let you know 👍

**Comment by mouradmourafiq** [comment]
Very strange that GCS allow to store `''` blob.

In any way a fix similar to what you proposed has been pushed. It will also be part of the v0.5.5 release.

**Comment by adam-phillipps** [comment]
I believe it's how they facilitate "folders" in the bucket but yeah, it's kind of an unexpected way to implement that, I agree.  In any case, thanks for taking a look and getting a fix out 👍
