### ISSUE TITLE
Bug: KeyError on s3 store ls command

### ISSUE THREAD

**Issue by AntonFriberg** [polyaxon/polystores#5]
Seems like there might be some form of degradation on the `s3_store`'s `ls` method.

Traceback:
```
Traceback (most recent call last):
  File "polystore_test.py", line 16, in <module>
    print(store.ls(path='polyaxon-outputs'))
  File "/home/antonfr/.virtualenvs/polyaxon/lib/python3.6/site-packages/polystores/stores/manager.py", line 51, in ls
    return self.store.ls(path)
  File "/home/antonfr/.virtualenvs/polyaxon/lib/python3.6/site-packages/polystores/stores/s3_store.py", line 208, in ls
    return {'files': results['blobs'], 'dirs': results['prefixes']}
KeyError: 'blobs'
```
Here is the `ls` method that is called in S3Store. https://github.com/polyaxon/polystores/blob/master/polystores/stores/s3_store.py#L206
```python
def ls(self, path):
    results = self.list(bucket_name=path)
    return {'files': results['blobs'], 'dirs': results['prefixes']}
```
However there is no concept of blobs in the case of s3 storage and `results` only contain the following keys: [`keys`, `prefixes`]

I see that both Azure and GCS have the concept of blobs in their stores which might have been the explanation for the error.

A simple fix would be to simply return `results['keys']`.

```diff
def ls(self, path):
    results = self.list(bucket_name=path)
-   return {'files': results['blobs'], 'dirs': results['prefixes']}
+   return {'files': results['keys'], 'dirs': results['prefixes']}
```
But this is probably not how the results are intended to be presented since the files are return as their entire path and no dirs are returned at all.

Here is a minimal example that I used together with a minio container to locate the bug.
```python
import os
from polystores.stores.manager import StoreManager

data_path = 's3://polyaxon-outputs'
os.environ['AWS_ENDPOINT_URL'] = 'http://localhost:9000'
os.environ['AWS_ACCESS_KEY_ID'] = 'key'
os.environ['AWS_SECRET_ACCESS_KEY'] = 'secret'
os.environ['AWS_REGION'] = 'us-east-1'
os.environ['POLYAXON_STORE'] = 's3'

store = StoreManager(path=data_path)

print(store.ls(path='polyaxon-outputs'))
```

**Comment by mouradmourafiq** [comment]
yes the change suggested is correct!
Not sure about the keys though, I need to try as well. 

I will fix the issue using the suggestion, and leave the keys for when I have time.

**Comment by mouradmourafiq** [comment]
I think this is fixed. closing the issue.
