### ISSUE TITLE
Folder creation fails if parent folder does not exists

### ISSUE THREAD

**Issue by AntonFriberg** [polyaxon/polystores#6]
Hi!

I think we want to use the `os.makedirs()` command and not the `os.mkdir()` in the stores `download_dir` methods. https://github.com/polyaxon/polystores/blob/master/polystores/stores/s3_store.py#L557

`os.makedirs()` is the recursive directory creation function.
https://docs.python.org/3.6/library/os.html#os.makedirs

I can create a PR if you agree!

**Comment by mouradmourafiq** [comment]
I think it makes sense.
If you want to make PR, please make the change in the other store as well, they all behave in the same way.
After merging, I will test it on GCS and Azure storage.

**Comment by AntonFriberg** [comment]
Will do!

**Comment by mouradmourafiq** [comment]
Great thanks 👍
